services:
  microbin:
    # Build locally first: LOCAL_DEV=true mr build-microbin
    image: microbin:dev
    restart: unless-stopped
    env_file: .env
    environment:
      # Non-default settings only
      MICROBIN_HIGHLIGHTSYNTAX: "true"
      MICROBIN_RENDER_MARKDOWN: "true"
      MICROBIN_RENDER_HTML: "true"
      MICROBIN_QR: "true"
      MICROBIN_SHOW_READ_STATS: "true"
      MICROBIN_EDITABLE: "false"
      MICROBIN_READONLY: "true"
      MICROBIN_ETERNAL_PASTA: "true"
      MICROBIN_HIDE_LOGO: "true"
      MICROBIN_DEFAULT_EXPIRY: "never"
      MICROBIN_GC_DAYS: 30
      MICROBIN_ENCRYPTION_CLIENT_SIDE: "true"
      MICROBIN_ENCRYPTION_SERVER_SIDE: "true"
      MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: 1024
      MICROBIN_DISABLE_TELEMETRY: "true"
      MICROBIN_DEFAULT_PRIVACY: "public"
    ports:
      - "9018:3000"
    volumes:
      - microbin_data:/app/microbin_data
    networks:
      - shared

volumes:
  microbin_data:

networks:
  shared:
    external: true
